# Numpy

In [3]:
!pip install numpy


##2D array

In [7]:
a_list = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
]

In [8]:
import numpy as np

In [18]:
np_array = np.array( a_list )
print(np_array)
print(type(np_array))
print(np_array[1])
print(np_array[1][1])
print(np_array[1, 1], '\n')# row index, column index - galima atskirti kableliu

print(np_array[ :, 0 ])# : rei6kia viska, 0 pirmas stulpelis
print(np_array[ :, 2 ], '\n')

print(np_array[ :2, 0 ], '\n')# pirmu dvieju eiliu

print(np_array[ :2, 1:3 ], '\n')# mazesne matrica

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>
[5 6 7 8]
6
6 

[1 5 9]
[ 3  7 11] 

[1 5] 

[[2 3]
 [6 7]] 



In [21]:
print( np_array.shape )# shape yra forma - 3 eilutes, 4 stulpeliai, po shape nera skliaustu

print( len(np_array) )# len ziuri tik i eiles

(3, 4)
3


In [22]:
print(np_array[ :2, 1:3 ].shape )

(2, 2)


#1D array

In [25]:
array_1d = np.array( [1,5,7,9,71,14] )

print( array_1d.shape )
print( len(array_1d) )
print( array_1d )#neraso kabelio

(6,)
6
[ 1  5  7  9 71 14]


In [30]:
list_1d = [1,5,7,9,71,14]
print( list_1d * 3) # atspausdins trys kartus
print ( [ number * 3 for number in list_1d ] )# jei sarasas
print ('numpy array')
print ( array_1d * 3 )
print ( array_1d / 3 )
print ( array_1d + 3 )
print ( array_1d % 2 )
print ( array_1d ** 5 )# penktuoju laipsniu


[1, 5, 7, 9, 71, 14, 1, 5, 7, 9, 71, 14, 1, 5, 7, 9, 71, 14]
[3, 15, 21, 27, 213, 42]
numpy array
[  3  15  21  27 213  42]
[ 0.33333333  1.66666667  2.33333333  3.         23.66666667  4.66666667]
[ 4  8 10 12 74 17]
[1 1 1 1 1 0]
[         1       3125      16807      59049 1804229351     537824]


In [33]:
print( array_1d )
print( list_1d )
list_1d[2:4] = [10,10]#sarasas,  pakeisti reiksmes, veikia jei nuordai abi reiksmes
print(list_1d)

print('numpy array')
array_1d[2:4] = [10,25]
print( array_1d )
array_1d[2:4] = 55#veikia ir su viena reiksme
print( array_1d )

[ 1  5 10 25 71 14]
[1, 5, 10, 10, 71, 14]
[1, 5, 10, 10, 71, 14]
numpy array
[ 1  5 10 25 71 14]
[ 1  5 55 55 71 14]


#3D array

In [50]:
arr_3d = np.array([
        [ 
            [1, 2, 3], 
            [4, 5, 6]
        ],
        [
            [1, 2, 3],
            [4, 5, 6]
        ]
    ]
)
print(arr_3d)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [51]:
print( arr_3d.shape )

(2, 2, 3)


In [52]:
arr_3d[:, :, 2] = 10# pakeisti tik paskutines reiksmes
print( arr_3d )

[[[ 1  2 10]
  [ 4  5 10]]

 [[ 1  2 10]
  [ 4  5 10]]]


In [54]:
arr_3d[1, 1, :2] = 55# antroj eilej pirmus du skaicius
print( arr_3d )

[[[ 1  2 10]
  [ 4  5 10]]

 [[ 1  2 10]
  [55 55 10]]]


# Numpy speed

In [56]:
size = 1_000_000

In [61]:
%%timeit # Jupyter komanda - kiek uztrunka skaiciavimas

py_list = list( range(size) )

48.6 ms ± 2.96 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [59]:
%%timeit

np_arr = np.arange(size)

2.84 ms ± 186 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [64]:
%%timeit
py_list = list( range(size) )

py_list_2 = [ number * 2 for number in py_list  ]

407 ms ± 46.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [66]:
%%timeit
np_arr = np.arange(size)
np_rez = np_arr * 2

7.43 ms ± 1.55 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


# Numpy reshape

In [67]:
np_array = np.arange(0,100,2)
print(np_array)
print(np_array.shape)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
(50,)


In [69]:
print(np_array.reshape( (5,10)), '\n')
print(np_array.reshape( (2,25)))

[[ 0  2  4  6  8 10 12 14 16 18]
 [20 22 24 26 28 30 32 34 36 38]
 [40 42 44 46 48 50 52 54 56 58]
 [60 62 64 66 68 70 72 74 76 78]
 [80 82 84 86 88 90 92 94 96 98]] 

[[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
  48]
 [50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96
  98]]


In [70]:
print(np_array.reshape( (5, 2, 5)))

[[[ 0  2  4  6  8]
  [10 12 14 16 18]]

 [[20 22 24 26 28]
  [30 32 34 36 38]]

 [[40 42 44 46 48]
  [50 52 54 56 58]]

 [[60 62 64 66 68]
  [70 72 74 76 78]]

 [[80 82 84 86 88]
  [90 92 94 96 98]]]


In [72]:
print(np_array.reshape( (2, 1, -1)))# -1 - palieka tiek kiek telpa

[[[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44
   46 48]]

 [[50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
   96 98]]]


# Numpy methods

In [73]:
array_3d = np.array( [
    [ [1,2], [4,3], [7,4] ],
    [ [2,2], [4,3], [7,4] ],
    [ [3,2], [4,3], [7,4] ],
    [ [4,2], [4,3], [7,4] ],
]
)
print( array_3d.shape)

(4, 3, 2)


In [74]:
print( array_3d)

[[[1 2]
  [4 3]
  [7 4]]

 [[2 2]
  [4 3]
  [7 4]]

 [[3 2]
  [4 3]
  [7 4]]

 [[4 2]
  [4 3]
  [7 4]]]


In [75]:
# paskaiciuoti vidurki

np.mean( array_3d )

3.75

In [89]:
print( 'matrix mean\n', np.mean( array_3d, axis = 0 ))# matricu vidurkis

matrix mean
 [[2.5 2. ]
 [4.  3. ]
 [7.  4. ]]


In [90]:
print('Column mean\n', np.mean( array_3d, axis = 1 ))# per stulpelius

Column mean
 [[4.         3.        ]
 [4.33333333 3.        ]
 [4.66666667 3.        ]
 [5.         3.        ]]


In [91]:
print('Row mean\n', np.mean( array_3d, axis = 2 ))# row

Row mean
 [[1.5 3.5 5.5]
 [2.  3.5 5.5]
 [2.5 3.5 5.5]
 [3.  3.5 5.5]]


In [80]:
np_array = np.arange(0,20).reshape( (5,4) )
print( np_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [86]:
np.mean( np_array, axis = 1 )# per visas eiles vidurki


array([ 1.5,  5.5,  9.5, 13.5, 17.5])

In [87]:
np.mean( np_array, axis = 0 )# per stulpeli vidurki
print('Column mean',  np.mean( np_array, axis=0 ) )
print('Row mean', np.mean( np_array, axis=1 ) )

Column mean [ 8.  9. 10. 11.]
Row mean [ 1.5  5.5  9.5 13.5 17.5]


In [93]:
print(np_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [92]:
np.std( np_array )# standartinis nuokrypis

5.766281297335398

In [94]:
print('Column std', np.std( np_array, axis = 0))
print('Row std', np.std( np_array, axis = 1))

Column std [5.65685425 5.65685425 5.65685425 5.65685425]
Row std [1.11803399 1.11803399 1.11803399 1.11803399 1.11803399]


In [95]:
print('Column sum', np.sum( np_array, axis = 0))
print('Row sum', np.sum( np_array, axis = 1))

Column sum [40 45 50 55]
Row sum [ 6 22 38 54 70]


In [97]:
print( np_array.shape ) # tranponuoti
print( np_array.T )
print( np_array.T.shape )

(5, 4)
[[ 0  4  8 12 16]
 [ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]]
(4, 5)


# Numpy comparison

In [102]:
rand_array = np.random.randint(7,50, 100)
print( rand_array )

[23 41 39 29 18 33 43 18 44 17 44 20  7 46 21 48 37 12 26 26 26 24 20 46
 33 10 22  8 43 10 15 29 36 26 41 12 18 17 13 34 15 45 12 25 42 12 49 25
 22 25  8 16 49 24 47 10 11 28  9  8 24 27 14 44 39 33 45  9 14 28 22 15
 45  7 36 31 39 46 48 38 46 34 10 35 21 49 10 14 46 13 14 15 22 29 32 14
 29  7 15 22]


In [101]:
#rand_array = np.random.randint(7,50, (5,50))
#print( rand_array )

In [103]:
rand_array[ rand_array > 18 ]

array([23, 41, 39, 29, 33, 43, 44, 44, 20, 46, 21, 48, 37, 26, 26, 26, 24,
       20, 46, 33, 22, 43, 29, 36, 26, 41, 34, 45, 25, 42, 49, 25, 22, 25,
       49, 24, 47, 28, 24, 27, 44, 39, 33, 45, 28, 22, 45, 36, 31, 39, 46,
       48, 38, 46, 34, 35, 21, 49, 46, 22, 29, 32, 29, 22])

In [104]:
rand_array[ rand_array > 30 ]

array([41, 39, 33, 43, 44, 44, 46, 48, 37, 46, 33, 43, 36, 41, 34, 45, 42,
       49, 49, 47, 44, 39, 33, 45, 45, 36, 31, 39, 46, 48, 38, 46, 34, 35,
       49, 46, 32])

In [105]:
rand_array > 30 # this is called a mask - kauke

array([False,  True,  True, False, False,  True,  True, False,  True,
       False,  True, False, False,  True, False,  True,  True, False,
       False, False, False, False, False,  True,  True, False, False,
       False,  True, False, False, False,  True, False,  True, False,
       False, False, False,  True, False,  True, False, False,  True,
       False,  True, False, False, False, False, False,  True, False,
        True, False, False, False, False, False, False, False, False,
        True,  True,  True,  True, False, False, False, False, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False,  True, False, False,  True, False,
       False, False, False, False,  True, False, False, False, False,
       False])

In [106]:
rand_array[ rand_array % 3 == 0 ]# gaunam skaicius kurie dalinasi is 3

array([39, 18, 33, 18, 21, 48, 12, 24, 33, 15, 36, 12, 18, 15, 45, 12, 42,
       12, 24,  9, 24, 27, 39, 33, 45,  9, 15, 45, 36, 39, 48, 21, 15, 15])

In [111]:
print( rand_array)

[23 41 39 29 18 33 43 18 44 17 44 20  7 46 21 48 37 12 26 26 26 24 20 46
 33 10 22  8 43 10 15 29 36 26 41 12 18 17 13 34 15 45 12 25 42 12 49 25
 22 25  8 16 49 24 47 10 11 28  9  8 24 27 14 44 39 33 45  9 14 28 22 15
 45  7 36 31 39 46 48 38 46 34 10 35 21 49 10 14 46 13 14 15 22 29 32 14
 29  7 15 22]


In [112]:
print( rand_array[ [0,1,2] ])# paduoti indeksus

[23 41 39]


In [113]:
print( rand_array[ [0,0,0] ])# paduoti indeksus

[23 23 23]


In [114]:
print( rand_array[ [0,21,-1,-2] ])# paduoti indeksus

[23 24 22 15]


# Pandas

In [115]:
!pip install pandas

     ---------------------------------------- 0.0/10.3 MB ? eta -:--:--
      --------------------------------------- 0.2/10.3 MB 7.0 MB/s eta 0:00:02
     -- ------------------------------------- 0.5/10.3 MB 8.5 MB/s eta 0:00:02
     ---- ----------------------------------- 1.0/10.3 MB 11.0 MB/s eta 0:00:01
     ----- ---------------------------------- 1.3/10.3 MB 10.4 MB/s eta 0:00:01
     ------- -------------------------------- 1.9/10.3 MB 11.2 MB/s eta 0:00:01
     --------- ------------------------------ 2.4/10.3 MB 10.8 MB/s eta 0:00:01
     ---------- ----------------------------- 2.8/10.3 MB 11.2 MB/s eta 0:00:01
     ------------ --------------------------- 3.3/10.3 MB 10.6 MB/s eta 0:00:01
     --------------- ------------------------ 3.9/10.3 MB 10.7 MB/s eta 0:00:01
     ----------------- ---------------------- 4.4/10.3 MB 10.9 MB/s eta 0:00:01
     ------------------- -------------------- 4.9/10.3 MB 10.8 MB/s eta 0:00:01
     -------------------- ------------------- 5.4/

In [116]:
import pandas as pd

In [117]:
df = pd.DataFrame(
    [ ['Jan',58,42,74,22,2.05],
    ['Feb',61,45,78,26,3.02],
    ['Mar',65,48,84,25,2.34],
    ['Apr',67,50,92,28,1.02],
    ['May',71,53,98,35,0.48],
    ['Jun',75,56,107,41,0.11],
    ['Jul',77,58,105,44,0.0],
    ['Aug',77,59,102,43,0.03],
    ['Sep',77,57,103,40,0.17],
    ['Oct',73,54,96,34,0.81],
    ['Nov',64,48,84,30,1.7],
    ['Dec',58,None,None,21,2.56],
    ['Dec',58,42,73,21,2.56] ],
    columns = ['month','avg_high','avg_low','record_high','record_low','avg_precipitation'])

In [118]:
df

month  avg_high  avg_low  record_high  record_low  avg_precipitation
0    Jan        58     42.0         74.0          22               2.05
1    Feb        61     45.0         78.0          26               3.02
2    Mar        65     48.0         84.0          25               2.34
3    Apr        67     50.0         92.0          28               1.02
4    May        71     53.0         98.0          35               0.48
5    Jun        75     56.0        107.0          41               0.11
6    Jul        77     58.0        105.0          44               0.00
7    Aug        77     59.0        102.0          43               0.03
8    Sep        77     57.0        103.0          40               0.17
9    Oct        73     54.0         96.0          34               0.81
10   Nov        64     48.0         84.0          30               1.70
11   Dec        58      NaN          NaN          21               2.56
12   Dec        58     42.0         73.0          21               2.56

In [119]:
df.info() # object - means string in Pandas

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   month              13 non-null     object 
 1   avg_high           13 non-null     int64  
 2   avg_low            12 non-null     float64
 3   record_high        12 non-null     float64
 4   record_low         13 non-null     int64  
 5   avg_precipitation  13 non-null     float64
dtypes: float64(3), int64(2), object(1)
memory usage: 752.0+ bytes


In [120]:
df.describe()# skaitines reiksmes ir atlieka pagrindines mat-nes reiksmes

avg_high    avg_low  record_high  record_low  avg_precipitation
count  13.000000  12.000000    12.000000   13.000000          13.000000
mean   67.769231  51.000000    91.333333   31.538462           1.296154
std     7.639305   6.060303    12.323911    8.501131           1.115210
min    58.000000  42.000000    73.000000   21.000000           0.000000
25%    61.000000  47.250000    82.500000   25.000000           0.170000
50%    67.000000  51.500000    94.000000   30.000000           1.020000
75%    75.000000  56.250000   102.250000   40.000000           2.340000
max    77.000000  59.000000   107.000000   44.000000           3.020000

In [121]:
df.head()# parodo pirmas 5 eilutes

month  avg_high  avg_low  record_high  record_low  avg_precipitation
0   Jan        58     42.0         74.0          22               2.05
1   Feb        61     45.0         78.0          26               3.02
2   Mar        65     48.0         84.0          25               2.34
3   Apr        67     50.0         92.0          28               1.02
4   May        71     53.0         98.0          35               0.48

In [122]:
df.head(3)# parodo pirmas 3 eilutes

month  avg_high  avg_low  record_high  record_low  avg_precipitation
0   Jan        58     42.0         74.0          22               2.05
1   Feb        61     45.0         78.0          26               3.02
2   Mar        65     48.0         84.0          25               2.34

In [123]:
df.tail()# parodo paskutines 5 eilutes

month  avg_high  avg_low  record_high  record_low  avg_precipitation
8    Sep        77     57.0        103.0          40               0.17
9    Oct        73     54.0         96.0          34               0.81
10   Nov        64     48.0         84.0          30               1.70
11   Dec        58      NaN          NaN          21               2.56
12   Dec        58     42.0         73.0          21               2.56

In [124]:
df.columns # stulpeliu title

Index(['month', 'avg_high', 'avg_low', 'record_high', 'record_low',
       'avg_precipitation'],
      dtype='object')

In [126]:
list( df.columns ) # stulpeliu title paverciame i list

['month',
 'avg_high',
 'avg_low',
 'record_high',
 'record_low',
 'avg_precipitation']

In [127]:
df.sort_values( 'avg_high' )# pagal koki stulpeli isrikiuoti

month  avg_high  avg_low  record_high  record_low  avg_precipitation
0    Jan        58     42.0         74.0          22               2.05
11   Dec        58      NaN          NaN          21               2.56
12   Dec        58     42.0         73.0          21               2.56
1    Feb        61     45.0         78.0          26               3.02
10   Nov        64     48.0         84.0          30               1.70
2    Mar        65     48.0         84.0          25               2.34
3    Apr        67     50.0         92.0          28               1.02
4    May        71     53.0         98.0          35               0.48
9    Oct        73     54.0         96.0          34               0.81
5    Jun        75     56.0        107.0          41               0.11
6    Jul        77     58.0        105.0          44               0.00
7    Aug        77     59.0        102.0          43               0.03
8    Sep        77     57.0        103.0          40               0.17

In [128]:
df.sort_values( 'avg_high', ascending=False )# pagal koki stulpeli isrikiuoti mazejimo tvarka

month  avg_high  avg_low  record_high  record_low  avg_precipitation
6    Jul        77     58.0        105.0          44               0.00
7    Aug        77     59.0        102.0          43               0.03
8    Sep        77     57.0        103.0          40               0.17
5    Jun        75     56.0        107.0          41               0.11
9    Oct        73     54.0         96.0          34               0.81
4    May        71     53.0         98.0          35               0.48
3    Apr        67     50.0         92.0          28               1.02
2    Mar        65     48.0         84.0          25               2.34
10   Nov        64     48.0         84.0          30               1.70
1    Feb        61     45.0         78.0          26               3.02
0    Jan        58     42.0         74.0          22               2.05
11   Dec        58      NaN          NaN          21               2.56
12   Dec        58     42.0         73.0          21               2.56

In [129]:
df.sort_values( ['avg_high', 'avg_low'], ascending=False )# pagal kokius stulpelius (kelis) isrikiuoti mazejimo tvarka


month  avg_high  avg_low  record_high  record_low  avg_precipitation
7    Aug        77     59.0        102.0          43               0.03
6    Jul        77     58.0        105.0          44               0.00
8    Sep        77     57.0        103.0          40               0.17
5    Jun        75     56.0        107.0          41               0.11
9    Oct        73     54.0         96.0          34               0.81
4    May        71     53.0         98.0          35               0.48
3    Apr        67     50.0         92.0          28               1.02
2    Mar        65     48.0         84.0          25               2.34
10   Nov        64     48.0         84.0          30               1.70
1    Feb        61     45.0         78.0          26               3.02
0    Jan        58     42.0         74.0          22               2.05
12   Dec        58     42.0         73.0          21               2.56
11   Dec        58      NaN          NaN          21               2.56

In [130]:
df.sort_values( ['avg_high', 'avg_low'], ascending= [False, True] )# kiekvienam stulpeliuj mazejimo ar didejimo

month  avg_high  avg_low  record_high  record_low  avg_precipitation
8    Sep        77     57.0        103.0          40               0.17
6    Jul        77     58.0        105.0          44               0.00
7    Aug        77     59.0        102.0          43               0.03
5    Jun        75     56.0        107.0          41               0.11
9    Oct        73     54.0         96.0          34               0.81
4    May        71     53.0         98.0          35               0.48
3    Apr        67     50.0         92.0          28               1.02
2    Mar        65     48.0         84.0          25               2.34
10   Nov        64     48.0         84.0          30               1.70
1    Feb        61     45.0         78.0          26               3.02
0    Jan        58     42.0         74.0          22               2.05
12   Dec        58     42.0         73.0          21               2.56
11   Dec        58      NaN          NaN          21               2.56

In [131]:
df# pandos nekeicia domenu, tik duoda atvaizdavima

month  avg_high  avg_low  record_high  record_low  avg_precipitation
0    Jan        58     42.0         74.0          22               2.05
1    Feb        61     45.0         78.0          26               3.02
2    Mar        65     48.0         84.0          25               2.34
3    Apr        67     50.0         92.0          28               1.02
4    May        71     53.0         98.0          35               0.48
5    Jun        75     56.0        107.0          41               0.11
6    Jul        77     58.0        105.0          44               0.00
7    Aug        77     59.0        102.0          43               0.03
8    Sep        77     57.0        103.0          40               0.17
9    Oct        73     54.0         96.0          34               0.81
10   Nov        64     48.0         84.0          30               1.70
11   Dec        58      NaN          NaN          21               2.56
12   Dec        58     42.0         73.0          21               2.56

In [132]:
# jei norim keisti duomenys
df_2 = df.sort_values( ['avg_high', 'avg_low'], ascending= [False, True] )
df_2

month  avg_high  avg_low  record_high  record_low  avg_precipitation
8    Sep        77     57.0        103.0          40               0.17
6    Jul        77     58.0        105.0          44               0.00
7    Aug        77     59.0        102.0          43               0.03
5    Jun        75     56.0        107.0          41               0.11
9    Oct        73     54.0         96.0          34               0.81
4    May        71     53.0         98.0          35               0.48
3    Apr        67     50.0         92.0          28               1.02
2    Mar        65     48.0         84.0          25               2.34
10   Nov        64     48.0         84.0          30               1.70
1    Feb        61     45.0         78.0          26               3.02
0    Jan        58     42.0         74.0          22               2.05
12   Dec        58     42.0         73.0          21               2.56
11   Dec        58      NaN          NaN          21               2.56

In [135]:
print (df_2[ 'record_low' ])  # paimti tam tikra stulpeli
print (type(df_2[ 'record_low' ]) )# vienas stulpelis ar eile - tai bus series

8     40
6     44
7     43
5     41
9     34
4     35
3     28
2     25
10    30
1     26
0     22
12    21
11    21
Name: record_low, dtype: int64
<class 'pandas.core.series.Series'>


In [137]:
print (df_2[ ['record_low', 'record_high' ] ])  # paimti kelis stulpelius
print (type(df_2[ ['record_low', 'record_high' ] ]))# dataframe nes keli stulpeliai,

    record_low  record_high
8           40        103.0
6           44        105.0
7           43        102.0
5           41        107.0
9           34         96.0
4           35         98.0
3           28         92.0
2           25         84.0
10          30         84.0
1           26         78.0
0           22         74.0
12          21         73.0
11          21          NaN
<class 'pandas.core.frame.DataFrame'>


In [138]:
df_2

month  avg_high  avg_low  record_high  record_low  avg_precipitation
8    Sep        77     57.0        103.0          40               0.17
6    Jul        77     58.0        105.0          44               0.00
7    Aug        77     59.0        102.0          43               0.03
5    Jun        75     56.0        107.0          41               0.11
9    Oct        73     54.0         96.0          34               0.81
4    May        71     53.0         98.0          35               0.48
3    Apr        67     50.0         92.0          28               1.02
2    Mar        65     48.0         84.0          25               2.34
10   Nov        64     48.0         84.0          30               1.70
1    Feb        61     45.0         78.0          26               3.02
0    Jan        58     42.0         74.0          22               2.05
12   Dec        58     42.0         73.0          21               2.56
11   Dec        58      NaN          NaN          21               2.56

In [139]:
#prideti nauja stulpeli
df_2[ 'naujas_stulpelis' ] = 5
df_2

month  avg_high  avg_low  record_high  record_low  avg_precipitation  \
8    Sep        77     57.0        103.0          40               0.17   
6    Jul        77     58.0        105.0          44               0.00   
7    Aug        77     59.0        102.0          43               0.03   
5    Jun        75     56.0        107.0          41               0.11   
9    Oct        73     54.0         96.0          34               0.81   
4    May        71     53.0         98.0          35               0.48   
3    Apr        67     50.0         92.0          28               1.02   
2    Mar        65     48.0         84.0          25               2.34   
10   Nov        64     48.0         84.0          30               1.70   
1    Feb        61     45.0         78.0          26               3.02   
0    Jan        58     42.0         74.0          22               2.05   
12   Dec        58     42.0         73.0          21               2.56   
11   Dec        58      NaN          NaN          21               2.56   

    naujas_stulpelis  
8                  5  
6                  5  
7                  5  
5                  5  
9                  5  
4                  5  
3                  5  
2                  5  
10                 5  
1                  5  
0                  5  
12                 5  
11                 5

In [141]:
df_2[ 'naujas_stulpelis2' ] = ( df_2 [ 'record_high' ] - df_2  [ 'record_low' ] )/ 2
df_2

month  avg_high  avg_low  record_high  record_low  avg_precipitation  \
8    Sep        77     57.0        103.0          40               0.17   
6    Jul        77     58.0        105.0          44               0.00   
7    Aug        77     59.0        102.0          43               0.03   
5    Jun        75     56.0        107.0          41               0.11   
9    Oct        73     54.0         96.0          34               0.81   
4    May        71     53.0         98.0          35               0.48   
3    Apr        67     50.0         92.0          28               1.02   
2    Mar        65     48.0         84.0          25               2.34   
10   Nov        64     48.0         84.0          30               1.70   
1    Feb        61     45.0         78.0          26               3.02   
0    Jan        58     42.0         74.0          22               2.05   
12   Dec        58     42.0         73.0          21               2.56   
11   Dec        58      NaN          NaN          21               2.56   

    naujas_stulpelis  naujas_stulpelis2  
8                  5               31.5  
6                  5               30.5  
7                  5               29.5  
5                  5               33.0  
9                  5               31.0  
4                  5               31.5  
3                  5               32.0  
2                  5               29.5  
10                 5               27.0  
1                  5               26.0  
0                  5               26.0  
12                 5               26.0  
11                 5                NaN

## loc[index]

In [142]:
# konkreti eilute - dazniau naudojama
df_2.loc[ 10 ] # reikia nurodyti eilutes indeksa

month                 Nov
avg_high               64
avg_low              48.0
record_high          84.0
record_low             30
avg_precipitation     1.7
naujas_stulpelis        5
naujas_stulpelis2    27.0
Name: 10, dtype: object

In [145]:
df_2.loc[ 8 ] 

month                  Sep
avg_high                77
avg_low               57.0
record_high          103.0
record_low              40
avg_precipitation     0.17
naujas_stulpelis         5
naujas_stulpelis2     31.5
Name: 8, dtype: object

## iloc[ row number ]

In [146]:
df_2.iloc[ 10 ]

month                 Jan
avg_high               58
avg_low              42.0
record_high          74.0
record_low             22
avg_precipitation    2.05
naujas_stulpelis        5
naujas_stulpelis2    26.0
Name: 0, dtype: object

In [147]:
df_2.iloc[ 0 ] # duoda poirma eilute

month                  Sep
avg_high                77
avg_low               57.0
record_high          103.0
record_low              40
avg_precipitation     0.17
naujas_stulpelis         5
naujas_stulpelis2     31.5
Name: 8, dtype: object

In [149]:
df_2

month  avg_high  avg_low  record_high  record_low  avg_precipitation  \
8    Sep        77     57.0        103.0          40               0.17   
6    Jul        77     58.0        105.0          44               0.00   
7    Aug        77     59.0        102.0          43               0.03   
5    Jun        75     56.0        107.0          41               0.11   
9    Oct        73     54.0         96.0          34               0.81   
4    May        71     53.0         98.0          35               0.48   
3    Apr        67     50.0         92.0          28               1.02   
2    Mar        65     48.0         84.0          25               2.34   
10   Nov        64     48.0         84.0          30               1.70   
1    Feb        61     45.0         78.0          26               3.02   
0    Jan        58     42.0         74.0          22               2.05   
12   Dec        58     42.0         73.0          21               2.56   
11   Dec        58      NaN          NaN          21               2.56   

    naujas_stulpelis  naujas_stulpelis2  
8                  5               31.5  
6                  5               30.5  
7                  5               29.5  
5                  5               33.0  
9                  5               31.0  
4                  5               31.5  
3                  5               32.0  
2                  5               29.5  
10                 5               27.0  
1                  5               26.0  
0                  5               26.0  
12                 5               26.0  
11                 5                NaN

In [148]:
df_2.loc[ 5:10 ]

month  avg_high  avg_low  record_high  record_low  avg_precipitation  \
5    Jun        75     56.0        107.0          41               0.11   
9    Oct        73     54.0         96.0          34               0.81   
4    May        71     53.0         98.0          35               0.48   
3    Apr        67     50.0         92.0          28               1.02   
2    Mar        65     48.0         84.0          25               2.34   
10   Nov        64     48.0         84.0          30               1.70   

    naujas_stulpelis  naujas_stulpelis2  
5                  5               33.0  
9                  5               31.0  
4                  5               31.5  
3                  5               32.0  
2                  5               29.5  
10                 5               27.0

In [151]:
df_2.loc[ [5,6,7,8,9,10] ]# tada teisingiau taip nurodyti

month  avg_high  avg_low  record_high  record_low  avg_precipitation  \
5    Jun        75     56.0        107.0          41               0.11   
6    Jul        77     58.0        105.0          44               0.00   
7    Aug        77     59.0        102.0          43               0.03   
8    Sep        77     57.0        103.0          40               0.17   
9    Oct        73     54.0         96.0          34               0.81   
10   Nov        64     48.0         84.0          30               1.70   

    naujas_stulpelis  naujas_stulpelis2  
5                  5               33.0  
6                  5               30.5  
7                  5               29.5  
8                  5               31.5  
9                  5               31.0  
10                 5               27.0

In [152]:
df_2.loc[ [5,6,7,8,9,10], 'avg_high' ]

5     75
6     77
7     77
8     77
9     73
10    64
Name: avg_high, dtype: int64

In [154]:
df_2.loc[ [5,6,7,8,9,10] , ['avg_high', 'record_high'] ] # pagrindine naudojama!
#df.loc[ row_indexes, column indexes]

avg_high  record_high
5         75        107.0
6         77        105.0
7         77        102.0
8         77        103.0
9         73         96.0
10        64         84.0

In [155]:
df_2.loc[ : , ['avg_high', 'record_high'] ]# visus stulpelius

avg_high  record_high
8         77        103.0
6         77        105.0
7         77        102.0
5         75        107.0
9         73         96.0
4         71         98.0
3         67         92.0
2         65         84.0
10        64         84.0
1         61         78.0
0         58         74.0
12        58         73.0
11        58          NaN

## changing row indexes

In [156]:
df_2

month  avg_high  avg_low  record_high  record_low  avg_precipitation  \
8    Sep        77     57.0        103.0          40               0.17   
6    Jul        77     58.0        105.0          44               0.00   
7    Aug        77     59.0        102.0          43               0.03   
5    Jun        75     56.0        107.0          41               0.11   
9    Oct        73     54.0         96.0          34               0.81   
4    May        71     53.0         98.0          35               0.48   
3    Apr        67     50.0         92.0          28               1.02   
2    Mar        65     48.0         84.0          25               2.34   
10   Nov        64     48.0         84.0          30               1.70   
1    Feb        61     45.0         78.0          26               3.02   
0    Jan        58     42.0         74.0          22               2.05   
12   Dec        58     42.0         73.0          21               2.56   
11   Dec        58      NaN          NaN          21               2.56   

    naujas_stulpelis  naujas_stulpelis2  
8                  5               31.5  
6                  5               30.5  
7                  5               29.5  
5                  5               33.0  
9                  5               31.0  
4                  5               31.5  
3                  5               32.0  
2                  5               29.5  
10                 5               27.0  
1                  5               26.0  
0                  5               26.0  
12                 5               26.0  
11                 5                NaN

In [157]:
df_3 = df_2.set_index('month')# menesi naudojam kaip indeksa
df_3

avg_high  avg_low  record_high  record_low  avg_precipitation  \
month                                                                  
Sep          77     57.0        103.0          40               0.17   
Jul          77     58.0        105.0          44               0.00   
Aug          77     59.0        102.0          43               0.03   
Jun          75     56.0        107.0          41               0.11   
Oct          73     54.0         96.0          34               0.81   
May          71     53.0         98.0          35               0.48   
Apr          67     50.0         92.0          28               1.02   
Mar          65     48.0         84.0          25               2.34   
Nov          64     48.0         84.0          30               1.70   
Feb          61     45.0         78.0          26               3.02   
Jan          58     42.0         74.0          22               2.05   
Dec          58     42.0         73.0          21               2.56   
Dec          58      NaN          NaN          21               2.56   

       naujas_stulpelis  naujas_stulpelis2  
month                                       
Sep                   5               31.5  
Jul                   5               30.5  
Aug                   5               29.5  
Jun                   5               33.0  
Oct                   5               31.0  
May                   5               31.5  
Apr                   5               32.0  
Mar                   5               29.5  
Nov                   5               27.0  
Feb                   5               26.0  
Jan                   5               26.0  
Dec                   5               26.0  
Dec                   5                NaN

In [158]:
df_3.loc[ 'Sep' ]

avg_high              77.00
avg_low               57.00
record_high          103.00
record_low            40.00
avg_precipitation      0.17
naujas_stulpelis       5.00
naujas_stulpelis2     31.50
Name: Sep, dtype: float64

In [159]:
df_3.loc[ ['Sep', 'Dec'] ]

avg_high  avg_low  record_high  record_low  avg_precipitation  \
month                                                                  
Sep          77     57.0        103.0          40               0.17   
Dec          58     42.0         73.0          21               2.56   
Dec          58      NaN          NaN          21               2.56   

       naujas_stulpelis  naujas_stulpelis2  
month                                       
Sep                   5               31.5  
Dec                   5               26.0  
Dec                   5                NaN

In [160]:
#df_3.iloc[ 'Sep' ]# error, iloc veikia ant eiluciu numeri nuo virsaus
df_3.iloc[ 0 ]# reikia  naudoti eiutes numeri

avg_high              77.00
avg_low               57.00
record_high          103.00
record_low            40.00
avg_precipitation      0.17
naujas_stulpelis       5.00
naujas_stulpelis2     31.50
Name: Sep, dtype: float64

In [162]:
# pasalinti kai kartuojasi duomenys
df_3 = df_3.dropna()#pasalina info kuriuos truksta. Standartiskai 0 ( trukstamas vertes), jei 1 - stulpelius
df_3

avg_high  avg_low  record_high  record_low  avg_precipitation  \
month                                                                  
Sep          77     57.0        103.0          40               0.17   
Jul          77     58.0        105.0          44               0.00   
Aug          77     59.0        102.0          43               0.03   
Jun          75     56.0        107.0          41               0.11   
Oct          73     54.0         96.0          34               0.81   
May          71     53.0         98.0          35               0.48   
Apr          67     50.0         92.0          28               1.02   
Mar          65     48.0         84.0          25               2.34   
Nov          64     48.0         84.0          30               1.70   
Feb          61     45.0         78.0          26               3.02   
Jan          58     42.0         74.0          22               2.05   
Dec          58     42.0         73.0          21               2.56   

       naujas_stulpelis  naujas_stulpelis2  
month                                       
Sep                   5               31.5  
Jul                   5               30.5  
Aug                   5               29.5  
Jun                   5               33.0  
Oct                   5               31.0  
May                   5               31.5  
Apr                   5               32.0  
Mar                   5               29.5  
Nov                   5               27.0  
Feb                   5               26.0  
Jan                   5               26.0  
Dec                   5               26.0

In [163]:
df_3.to_csv('weather.csv')# pasirenki kokiu formatu issaugoti